$numDocumentoIdObligado ='';
$codsexo='';
$codzona='';
$fechaatencion = '';

$sql = "SELECT numeroidentificacion nit, razonsocial, codigoprestador, prefijo FROM prestadorservicios";
sc_select(rsp,$sql);
if(!$rsp->EOF){
	$idPrestador = $rsp->fields['codigoprestador'];
	$razonsocial = $rsp->fields['razonsocial'];
	$nit =  $rsp->fields['nit'];
}

$sql="SELECT t1.fecha, t1.hora, t1.fechafin, t1.horafin, t1.codigo, t3.nombre as tipoidentificacion, t1.cedulapaciente, t2.apellido, t2.nombre, CONCAT(t2.nombre, ' ', t2.apellido) as paciente, t2.direccion, t2.telefonocelular, t4.estadocivil, t2.fechanacimiento, t1.edad, t2.sexo, t7.nombre as sexonombre, t5.nombre as entidadnombre, t1.fecha, t1.hora, t1.motivoconsulta, t1.examenfisico, t1.detalle as enfermedad_actual, t1.coddiagppal, t6.nombre as diagppal, t1.conclusiones, t1.clave as idprofesional, t8.nombre as nombremedico, t8.registromedico, t8.firma, t1.antecedente
FROM historiacontroles t1 INNER JOIN historiaclinica t2 ON t2.numeroidentificacion = t1.cedulapaciente 
INNER JOIN tipoidentificacion t3 ON t3.codigo =t2.tipoidentificacion
INNER JOIN estadocivil t4 ON t4.codigo=t2.estadocivil 
INNER JOIN entidades t5 ON t5.Codigo = t1.entidad 
INNER JOIN diagnosticos t6 ON t6.codigo=t1.coddiagppal
INNER JOIN sexo t7 ON t7.codigo = t2.sexo
INNER JOIN usuarios t8 ON t8.cedula = t1.clave
WHERE t1.codigo = '1027516126-02-2026 09:19:18'";

sc_select(rs,$sql);

if(!$rs->EOF){
	$consecutivousuarios =0;
	while (!$rs->EOF){
		$dxppal = '';
		$dxrel1 = '';
		$control = $rs->fields['control'];
		$idmedico= $rs->fields['clave'];
		$factura = $rs->fields['nofactura'];
		$idpaciente = '#CC' . $rs->fields['cedulapaciente'];
		$apellidos = $rs->fields['apellido'];
		$nombres = $rs->fields['nombre'];
		$fechanacimiento = $rs->fields['fechanacimiento'];
		if($rs->fields['sexo']==0){
			$genero = 'Hombre';
		} 
		if($rs->fields['sexo']==1){
			$genero = 'Mujer';
		} 
		
		$fechaActual = new DateTime('now', new DateTimeZone('UTC'));
		$timestampRDA = $fechaActual->format("Y-m-d\TH:i:s\Z");
		$ruta = "/var/www/html/xeniamm/";
		
		$archivo_ruta = $ruta . 'RDA' . $factura . ".json";
		$archivo = fopen($archivo_ruta, "w+b");
		if( $archivo == false ){
			// Error al crear el archivo
		}else{
			$linea = '{';	
			fwrite($archivo, $linea . "\r\n");		
			$linea = '"resourceType": "Bundle",';
			fwrite($archivo, $linea . "\r\n");
			$linea = '"language": "es-CO",';
            fwrite($archivo, $linea . "\r\n");      
			$linea = '"type": "document",';
            fwrite($archivo, $linea . "\r\n");
			$linea = '"entry": [';
            fwrite($archivo, $linea . "\r\n");
				$linea = '{';   
                    fwrite($archivo, $linea . "\r\n");
					$linea = '"resource": {';
                    fwrite($archivo, $linea . "\r\n");
						$linea = '"resourceType": "Composition",';
                        fwrite($archivo, $linea . "\r\n");
						$linea = '"meta": {';
                            fwrite($archivo, $linea . "\r\n");
							$linea = '"profile": [';
                            fwrite($archivo, $linea . "\r\n");
								$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/CompositionPatientStatementRDA"';
                                fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
						$linea = '"status": "final",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"type": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"coding": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '{';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"system": "http://loinc.org",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"code": "102089-0",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"display": "FHIR resource patient medical record"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"subject": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"reference": "'. $idpaciente .'"';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"date": "' . $fechaFinAtencion . '",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"author": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"reference": "' . $idmedico . '"';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = '],';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"title": "Resumen Digital de AtenciÃ³n en Salud - RDA de antecedentes manifestados por el paciente",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"confidentiality": "N",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"attester": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"mode": "legal",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"party": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"reference": "'. $idPrestador .'"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = '],';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"custodian": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"reference": "'. $idPrestador .'"';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"event": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"code": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '{';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"coding": [';
										fwrite($archivo, $linea . "\r\n");
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianTechModality",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"code": "01",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"display": "Intramural"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
										$linea = ']';
										fwrite($archivo, $linea . "\r\n");
									$linea = '},';
									fwrite($archivo, $linea . "\r\n");
									$linea = '{';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"coding": [';
										fwrite($archivo, $linea . "\r\n");
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/GrupoServicios",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"code": "01",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"display": "Consulta externa"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
										$linea = ']';
										fwrite($archivo, $linea . "\r\n");
									$linea = '}';
									fwrite($archivo, $linea . "\r\n");
								$linea = '],';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"period": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"start": "' . $fechaIniAtencion . '",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"end": "' . $fechaFinAtencion . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = '],';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"section": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"title": "Historial de diagnÃ³sticos de problemas de salud",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"code": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://loinc.org",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "11450-4",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Problem list - Reported"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"entry": [';
								fwrite($archivo, $linea . "\r\n");
									//verificar si tiene antecedentes de condiciones de salud
									$sql = "SELECT dxcie1o FROM historia_dx_1888 WHERE control = '" . [glo_codigoControl] . "'";
									sc_select(rscs,$sql);
									if(!$rscs->EOF){
										$numerocondicion = 1;
										while(!$rscs->EOF){			
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$condicionreferencia = '#Condition-' . $numerocondicion;
												$linea = '"reference": "' . $condicionreferencia . '"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
											$numerocondicion = $numerocondicion +1;	
											$rscs->MoveNext();
										}
									}else{
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"reference": "#Condition-NoConocida"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									}
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"title": "Historial de alergias, intolerancias y reacciones adversas",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"code": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://loinc.org",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "48765-2",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Allergies and adverse reactions Document"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"entry": [';
								fwrite($archivo, $linea . "\r\n");
									//verificar si tiene antecedentes de alergias
									$sql = "SELECT id_alergia, nombre_alergeno FROM historia_ant_alergias_1888 WHERE control = '" . [glo_codigoControl] . "'";
									sc_select(rsaa,$sql);
									if(!$rsaa->EOF){
										$numeroalergia = 1;
										while(!$rsaa->EOF){
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$alergiareferencia = '#AllergyIntolerance-' . $numeroalergia;
												$linea = '"reference": "'. $alergiareferencia .'"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
											$numeroalergia =$numeroalergia+1;
											$rsaa->MoveNext();
										}
									}else{
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"reference": "#AllergyIntolerance-NoConocida"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									};	
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"title": "Historial de medicamentos",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"code": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://loinc.org",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "10160-0",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "History of Medication use Narrative"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"entry": [';
								fwrite($archivo, $linea . "\r\n");
									//verificar si tiene antecedentes farmacologicos
									$sql = "SELECT id_dci FROM historia_antfarmacologicos_1888 WHERE control = '" . [glo_codigoControl] . "'";
									sc_select(rscs,$sql);
									if(!$rscs->EOF){
										$numeromedicamento = 1;
										while(!$rscs->EOF){
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$medicamemtoreferencia = '#MedicationStatement-' . $numeromedicamento; 	
												$linea = '"reference": "' . $medicamemtoreferencia . '"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
											$numeromedicamento = $numeromedicamento +1;	
											$rscs->MoveNext();
										}
									}else{												
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"reference": "#MedicationStatement-NoConocida"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';	
										fwrite($archivo, $linea . "\r\n");
									}
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"title": "Historial de antecedentes familiares",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"code": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://loinc.org",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "10157-6",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "History of family member diseases Narrative"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"entry": [';
								fwrite($archivo, $linea . "\r\n");
									//verificar si tiene antecedentes familiares de salud
									$sql = "SELECT dxcie1o, parentezco FROM historia_familiar_1888 WHERE control = '" . [glo_codigoControl] . "'";
									sc_select(rscs,$sql);
									if(!$rscs->EOF){
										$numerofamily = 1;
										while(!$rscs->EOF){			
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$familyreferencia = '#FamilyMemberHistory-' . $numerofamily;
												$linea = '"reference": "' . $familyreferencia . '"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
											$numerofamily = $numerofamily +1;	
											$rscs->MoveNext();
										}
									}else{												
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"reference": "#FamilyMemberHistory-NoConocida"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';	
										fwrite($archivo, $linea . "\r\n");
									}
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
					$linea = '}';
					fwrite($archivo, $linea . "\r\n");
				$linea = '},';
				fwrite($archivo, $linea . "\r\n");
				$linea = '{';
				fwrite($archivo, $linea . "\r\n");
					$linea = '"resource": {';
					fwrite($archivo, $linea . "\r\n");
						$linea = '"resourceType": "Patient",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"id": "' . $idpaciente . '",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"meta": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"profile": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/PatientRDA"';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"extension": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionPatientNationality",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"valueCoding": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ISO31661",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"code": "170",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"display": "Colombia"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionPatientEthnicity",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"valueCoding": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianEthnicGroup",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"code": "' . $codetnia . '",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"display": "' . $nombretnia . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionPatientDisability",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"valueCoding": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianDisabilityClassification",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"code": "' . $coddiscapacidad . '",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"display": "' . $nombrediscapacidad . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionPatientGenderIdentity",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"valueCoding": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianGenderIdentity",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"code": "' . $codsexo . '",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"display": "' . $nombresexo . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"identifier": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"type": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://terminology.hl7.org/CodeSystem/v2-0203",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "PN",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Person number"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianPersonIdentifier",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "' . $tipoidenpaciente . '",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $nombretipoidenpaciente . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"id": "NationalPersonIdentifier-0",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"use": "official",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"system": "https://fhir.minsalud.gov.co/rda/NamingSystem/RNEC",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"value": "' . $idpaciente . '"';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"name": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"given": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"' . $primerNombre . '",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"' . $segundoNombre . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '],';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"use": "official",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"family": "' . $apellidos . '",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"_family": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"extension": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionFathersFamilyName",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"valueString": "' . $primerApellido . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionMothersFamilyName",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"valueString": "' . $segundoApellido . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"address": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"id": "HomeAddress-0",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"use": "home",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"type": "physical",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"city": "' . $nombremunicipiopaciente . '",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"_city": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"extension": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionDivipolaMunicipality",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"valueCoding": {';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"code": "' . $ciudaddirpaciente . '",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/DIVIPOLA"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"country": "Colombia",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"_country": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"extension": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionCountryCode",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"valueCoding": {';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ISO31661",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"code": "170"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"extension": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '{';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionResidenceZone",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"valueCoding": {';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianResidenceZone",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "' . $codzona . '",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $nombrezona . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = '}';
									fwrite($archivo, $linea . "\r\n");
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"active": true,';
						fwrite($archivo, $linea . "\r\n");
						
						$linea = '"gender": "' . $genero . '",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"_gender": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"extension": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '{';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionBiologicalGender",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"valueCoding": {';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianGenderGroup",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"code": "' . $codidengenero . '",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"display": "' .$nomidengenero . '"';
										fwrite($archivo, $linea . "\r\n");
									$linea = '}';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"birthDate": "' . $fechanacimiento . '",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"_birthDate": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"extension": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '{';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionBirthTime",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"valueTime": ""';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"deceasedBoolean": false';
						fwrite($archivo, $linea . "\r\n");
					$linea = '}';
					fwrite($archivo, $linea . "\r\n");
				$linea = '},';
				fwrite($archivo, $linea . "\r\n");
				$linea = '{';
				fwrite($archivo, $linea . "\r\n");
					$linea = '"resource": {';
					fwrite($archivo, $linea . "\r\n");
						$linea = '"resourceType": "Organization",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"id": "CÃ³digohabilitaciÃ³nprestador",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"meta": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"profile": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/CareDeliveryOrganizationRDA"';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"identifier": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"id": "TaxIdentifier-0",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"use": "official",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"type": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://terminology.hl7.org/CodeSystem/v2-0203",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "TAX",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Tax ID number"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianOrganizationIdentifiers",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "NIT",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $nit . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"value": "' . $razonsocial . '"';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"id": "HealthcareProviderIdentifier-0",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"use": "official",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"type": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://terminology.hl7.org/CodeSystem/v2-0203",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "PRN",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Provider number"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianOrganizationIdentifiers",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "CodigoPrestador",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $idPrestador . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"system": "https://fhir.minsalud.gov.co/rda/NamingSystem/REPS",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"value": "' . $idPrestador . '"';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
					$linea = '}';
					fwrite($archivo, $linea . "\r\n");
				$linea = '},';
				fwrite($archivo, $linea . "\r\n");
				$linea = '{';
				fwrite($archivo, $linea . "\r\n");
					$linea = '"resource": {';
					fwrite($archivo, $linea . "\r\n");
						$linea = '"resourceType": "Practitioner",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"id": "CC-1111111111",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"meta": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"profile": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/PractitionerRDA"';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"identifier": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"id": "NationalPersonIdentifier-0",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"use": "official",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"type": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://terminology.hl7.org/CodeSystem/v2-0203",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "PN",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Person number"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ColombianPersonIdentifier",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "' . $tipoidenmedico . '",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $cedulamedico . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"value": "' . $idmedico . '"';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"name": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"use": "official",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"family": "' . $apellidosmedico . '",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"_family": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"extension": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionFathersFamilyName",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"valueString": "' . $primerapellidomedico . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"url": "https://fhir.minsalud.gov.co/rda/StructureDefinition/ExtensionMothersFamilyName",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"valueString": "' . $segundoapellidomedico . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"given": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"' . $primernombremedico . '",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"' . $segundonombremedico . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = ']';
						fwrite($archivo, $linea . "\r\n");
					$linea = '}';
					fwrite($archivo, $linea . "\r\n");
				$linea = '},';
				fwrite($archivo, $linea . "\r\n");
				$linea = '{';
				fwrite($archivo, $linea . "\r\n");
					//verificar si tiene antecedentes de condiciones de salud
					$sql = "SELECT t1.dxcie10, t2.nombre as nombredxcie10 FROM historia_dx_1888 t1 INNER JOIN diagnosticos t2 ON t2.codigo = t1.dxcie10 WHERE t1.control = '" . [glo_codigoControl] . "'";
					sc_select(rscs,$sql);
					if(!$rscs->EOF){
						$numerocondicion = 1;
						while(!$rscs->EOF){
							$dxcie10 = $rscs->fields['dxcie10'];
							$nombredxcie10 = $rscs->fields['nombredxcie10'];
							
							$linea = '"resource": {';
							fwrite($archivo, $linea . "\r\n");
							$linea = '"resourceType": "Condition",';
							fwrite($archivo, $linea . "\r\n");
							$condicionnumero = 'Condition-' . $numerocondicion;
							$linea = '"id": "' . $condicionnumero .'",';
							fwrite($archivo, $linea . "\r\n");
							$linea = '"meta": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"profile": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/ConditionStatementRDA"';
									fwrite($archivo, $linea . "\r\n");
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '"clinicalStatus": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"coding": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '{';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"code": "active",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"system": "http://terminology.hl7.org/CodeSystem/condition-clinical",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"display": "Active"';
										fwrite($archivo, $linea . "\r\n");
									$linea = '}';
									fwrite($archivo, $linea . "\r\n");
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '"verificationStatus": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"coding": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '{';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"code": "unconfirmed",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"display": "Unconfirmed"';
										fwrite($archivo, $linea . "\r\n");
									$linea = '}';
									fwrite($archivo, $linea . "\r\n");
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '"category": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '{';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://terminology.hl7.org/CodeSystem/condition-category",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "' . $dxcie10 . '",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $nombredxcie10 . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '],';
							fwrite($archivo, $linea . "\r\n");
							$linea = '"code": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"text": "' . $nombredxcie10 . '"';
								fwrite($archivo, $linea . "\r\n");
							$linea = '},';
							fwrite($archivo, $linea . "\r\n");
							$linea = '"subject": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"reference": "' . $idpaciente . '"';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = '}';
						fwrite($archivo, $linea . "\r\n");
						$numerocondicion = $numerocondicion + 1;
						$rscs->MoveNext();
						}	
					}else{
						$linea = '"resource": {';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"resourceType": "Condition",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"id": "Condition-0",';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"meta": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"profile": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/ConditionStatementRDA"';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"clinicalStatus": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"coding": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '{';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"code": "active",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"system": "http://terminology.hl7.org/CodeSystem/condition-clinical",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"display": "Active"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"verificationStatus": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"coding": [';
							fwrite($archivo, $linea . "\r\n");
								$linea = '{';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"code": "unconfirmed",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"display": "Unconfirmed"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = ']';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"category": [';
						fwrite($archivo, $linea . "\r\n");
							$linea = '{';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"coding": [';
								fwrite($archivo, $linea . "\r\n");
									$linea = '{';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"system": "http://terminology.hl7.org/CodeSystem/condition-category",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"code": "Sin antecedentes o condiciones de salud relevantes",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"display": "Sin antecedentes o condiciones de salud relevantes"';
										fwrite($archivo, $linea . "\r\n");
									$linea = '}';
									fwrite($archivo, $linea . "\r\n");
								$linea = ']';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = '],';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"code": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"text": "Sin antecedentes o condiciones de salud relevantes"';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
						$linea = '"subject": {';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"reference": "'. $idpaciente . '"';
							fwrite($archivo, $linea . "\r\n");
						$linea = '}';
						fwrite($archivo, $linea . "\r\n");
					$linea = '}';
					fwrite($archivo, $linea . "\r\n");
					}	
				$linea = '},';
				fwrite($archivo, $linea . "\r\n");
			
				$linea = '{';
				fwrite($archivo, $linea . "\r\n");
					//verificar si tiene antecedentes de alergias
					$sql = "SELECT t1.id_alergia, t2.tipo_antecedente, t1.nombre_alergeno
FROM historia_ant_alergias_1888 t1 INNER JOIN ant_alergicos_1888 t2 ON t2.id=t1.id_alergia WHERE t1.control = '" . [glo_codigoControl] . "'";
					sc_select(rsaa,$sql);
					if(!$rsaa->EOF){
						$numeroalergia = 1;
						$codigoAlergia = $rsaa->fields['id_alergia'];
						$tipoAntAlergia = $rsaa->fields['tipo_antecedente'];
						$nombreAlergeno = $rsaa->fields['nombre_alergeno'];
						while(!$rsaa->EOF){
							$linea = '"resource": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"resourceType": "AllergyIntolerance",';
								fwrite($archivo, $linea . "\r\n");
								$alergiareferencia = '#AllergyIntolerance-' . $numeroalergia;
								$linea = '"id": "' . $numeroalergia . '",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"meta": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"profile": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/AllergyIntoleranceStatementRDA"';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"clinicalStatus": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "active",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Active"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"verificationStatus": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "unconfirmed",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "Unconfirmed"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"code": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/TipoAlergia",';
											fwrite($archivo, $linea . "\r\n");
											
											$linea = '"code": "' . $codigoAlergia . '",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $tipoAntAlergia . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = '],';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"text": "'. $nombreAlergeno .'"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"patient": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"reference": "' . $idpaciente . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
							$numeroalergia = $numeroalergia + 1;
							$rsaa->MoveNext();
						}	
					}else{
						$linea = '{';
						fwrite($archivo, $linea . "\r\n");
							$linea = '"resource": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"resourceType": "AllergyIntolerance",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"id": "AllergyIntolerance-NoConocida",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"clinicalStatus": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://terminology.hl7.org/CodeSystem/condition-clinical",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "active"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"code": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "http://snomed.info/sct",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "716186003",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "No conocida alergia a fÃ¡rmaco"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = '],';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"text": "SIN ALERGIAS CONOCIDAS"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"patient": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"reference": "' . $idpaciente . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
						$linea = '},';
						fwrite($archivo, $linea . "\r\n");
					
					}	
				$linea = '},';
				fwrite($archivo, $linea . "\r\n");
						
				$linea = '{';
				fwrite($archivo, $linea . "\r\n");
								//verificar si tiene antecedentes familiares de salud
							 	$sql = "SELECT dxcie10, parentezco as cod_parentezco, t2.parentezco as nombreparentezco, t3.nombre as nombredx FROM historia_familiar_1888 t1 INNER JOIN parentezco t2 ON t2.codigo = t1.parentezco INNER JOIN diagnosticos t3 ON t3.codigo = t1.dxcie10 WHERE t1.control = '" . [glo_codigoControl] . "'";
								sc_select(rscs,$sql);
								if(!$rscs->EOF){
									$numerofamily = 1;
									while(!$rscs->EOF){	
										$coddxparentezco = $rscs->fields['dxcie10'];
										$nombredx = $rscs->fields['nombredx'];
										$codparentezco = $rscs->fields['cod_parentezco'];
										$nombreparentezco = $rscs->fields['nombreparentezco'];
										$linea = '"resource": {';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"resourceType": "FamilyMemberHistory",';
										fwrite($archivo, $linea . "\r\n");
										$familynumero = 'FamilyMemberHistory-' . $numerofamily;
										$linea = '"id": "' . $familynumero . '",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"meta": {';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"profile": [';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/FamilyMemberHistoryRDA"';
												fwrite($archivo, $linea . "\r\n");
											$linea = ']';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"status": "partial",';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"patient": {';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"reference": "' . $idpaciente . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"relationship": {';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"coding": [';
											fwrite($archivo, $linea . "\r\n");
												$linea = '{';
												fwrite($archivo, $linea . "\r\n");
													$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ParentescoAntecedente",';
													fwrite($archivo, $linea . "\r\n");
													$linea = '"code": "' . $codparentezco . '",';
													fwrite($archivo, $linea . "\r\n");
													$linea = '"display": "' . $nombreparentezco . '"';
													fwrite($archivo, $linea . "\r\n");
												$linea = '}';
												fwrite($archivo, $linea . "\r\n");
											$linea = ']';
											fwrite($archivo, $linea . "\r\n");
										$linea = '},';
										fwrite($archivo, $linea . "\r\n");
										$linea = '"condition": [';
										fwrite($archivo, $linea . "\r\n");
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"code": {';
												fwrite($archivo, $linea . "\r\n");
													$linea = '"coding": [';
													fwrite($archivo, $linea . "\r\n");
														$linea = '{';
														fwrite($archivo, $linea . "\r\n");
															$linea = '"system": "http://hl7.org/fhir/sid/icd-10",';
															fwrite($archivo, $linea . "\r\n");
															$linea = '"code": "' . $coddxparentezco . '",';
															fwrite($archivo, $linea . "\r\n");
															$linea = '"display": "' . $nombredx . '"';
															fwrite($archivo, $linea . "\r\n");
														$linea = '}';
														fwrite($archivo, $linea . "\r\n");
													$linea = ']';
													fwrite($archivo, $linea . "\r\n");
												$linea = '}';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
										$linea = ']';
										fwrite($archivo, $linea . "\r\n");
									$linea = '}';
									fwrite($archivo, $linea . "\r\n");
									$numerofamily = $numerofamily + 1;
									$rscs->MoveNext();
									}	
								}else{
									$linea = '"resource": {';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"resourceType": "FamilyMemberHistory",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"id": "FamilyMemberHistory-0",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"meta": {';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"profile": [';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/FamilyMemberHistoryRDA"';
											fwrite($archivo, $linea . "\r\n");
										$linea = ']';
										fwrite($archivo, $linea . "\r\n");
									$linea = '},';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"status": "partial",';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"patient": {';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"reference": "' . $idpaciente . '"';
										fwrite($archivo, $linea . "\r\n");
									$linea = '},';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"relationship": {';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"coding": [';
										fwrite($archivo, $linea . "\r\n");
											$linea = '{';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/ParentescoAntecedente",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"code": "01",';
												fwrite($archivo, $linea . "\r\n");
												$linea = '"display": "Padres"';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
										$linea = ']';
										fwrite($archivo, $linea . "\r\n");
									$linea = '},';
									fwrite($archivo, $linea . "\r\n");
									$linea = '"condition": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"code": {';
											fwrite($archivo, $linea . "\r\n");
												$linea = '"coding": [';
												fwrite($archivo, $linea . "\r\n");
													$linea = '{';
													fwrite($archivo, $linea . "\r\n");
														$linea = '"system": "http://hl7.org/fhir/sid/icd-10",';
														fwrite($archivo, $linea . "\r\n");
														$linea = '"code": "",';
														fwrite($archivo, $linea . "\r\n");
														$linea = '"display": "SIN ANTECEDENTES FAMILIARES"';
														fwrite($archivo, $linea . "\r\n");
													$linea = '}';
													fwrite($archivo, $linea . "\r\n");
												$linea = ']';
												fwrite($archivo, $linea . "\r\n");
											$linea = '}';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';						
								fwrite($archivo, $linea . "\r\n");
								}
				$linea = '},';
				fwrite($archivo, $linea . "\r\n");
						
				$linea = '{';
				fwrite($archivo, $linea . "\r\n");
					//verificar si tiene antecedentes farmacologicos
					$sql = "SELECT t1.id_dci, t2.nombre as nombremedicamento FROM historia_antfarmacologicos_1888 t1 INNER JOIN medgenerico t2 ON t2.codigo = t1.id_dci WHERE t1.control = '" . [glo_codigoControl] . "'";
					sc_select(rscs,$sql);
					if(!$rscs->EOF){
						$numeromedicamento = 1;
						while(!$rscs->EOF){	
							$codmed = $rscs->fields['id_dci'];
							$nombremed = $rscs->fields['nombremedicamento'];
							$linea = '"resource": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"resourceType": "MedicationStatement",';
								fwrite($archivo, $linea . "\r\n");
								$medicamentonumero = 'MedicationStatement-' . $numeromedicamento;
								$linea = '"id": "' . $medicamentonumero . '",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"meta": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"profile": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/MedicationStatementRDA"';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"status": "completed",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"medicationCodeableConcept": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/MipresINN",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "' . $codmed . '",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "' . $nombremed . '"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"subject": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"reference": "' . $idpaciente . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
							$numeromedicamento = $numeromedicamento + 1;
							$rscs->MoveNext();
						}	
					}else{
							$linea = '"resource": {';
							fwrite($archivo, $linea . "\r\n");
								$linea = '"resourceType": "MedicationStatement",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"id": "MedicationStatement-0",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"meta": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"profile": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '"https://fhir.minsalud.gov.co/rda/StructureDefinition/MedicationStatementRDA"';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"status": "completed",';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"medicationCodeableConcept": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"coding": [';
									fwrite($archivo, $linea . "\r\n");
										$linea = '{';
										fwrite($archivo, $linea . "\r\n");
											$linea = '"system": "https://fhir.minsalud.gov.co/rda/CodeSystem/MipresINN",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"code": "",';
											fwrite($archivo, $linea . "\r\n");
											$linea = '"display": "SIN ANTECEDENTES FARMACOLOGICOS"';
											fwrite($archivo, $linea . "\r\n");
										$linea = '}';
										fwrite($archivo, $linea . "\r\n");
									$linea = ']';
									fwrite($archivo, $linea . "\r\n");
								$linea = '},';
								fwrite($archivo, $linea . "\r\n");
								$linea = '"subject": {';
								fwrite($archivo, $linea . "\r\n");
									$linea = '"reference": "' . $idpaciente . '"';
									fwrite($archivo, $linea . "\r\n");
								$linea = '}';
								fwrite($archivo, $linea . "\r\n");
							$linea = '}';
							fwrite($archivo, $linea . "\r\n");
					}	
				$linea = '}';
				fwrite($archivo, $linea . "\r\n");
						
						
			$linea = ']';
			fwrite($archivo, $linea . "\r\n");
			$linea = '}';
			fwrite($archivo, $linea . "\r\n");
		
			fclose($archivo);
			[glo_archivo] = $factura . ".json";
		}	

		//sc_redir(blank_archivo_json);

	$rs->MoveNext();

	}
}
	
echo "PROCESO TERMINADO ";

// fwrite($archivo, $linea . "\r\n");
